version: "3"
services:
  ideas-db:
    container_name: ideas-db
    image: mongo:4.0
    ports:
      - 27017:27017
  gateway:
    container_name: gateway
    build:
      context: ./
      dockerfile: ./docker-images/production/gateway/Gateway.Dockerfile
    ports:
      - 3000:3000
    env_file: ./env/.env.production
  ideas:
    container_name: ideas
    build:
      context: ./
      dockerfile: ./docker-images/production/ideas/Ideas.Dockerfile
    env_file: ./env/.env.production
