version: '3'
services:
  gateway:
    container_name: gateway
    build:
      context: ./
      dockerfile: ./docker-images/gateway/Gateway.dev.Dockerfile
    volumes:
      - ./services/gateway/dist:/usr/app/src/services/gateway/dist
      - ./packages/utils/dist:/usr/app/src/packages/utils/dist
      - ./node_modules:/usr/app/src/node_modules
    ports:
      - 3000:3000
  ideas:
    container_name: ideas
    build:
      context: ./
      dockerfile: ./docker-images/ideas/Ideas.dev.Dockerfile
    volumes:
      - ./services/ideas/dist:/usr/app/src/services/ideas/dist
      - ./packages/utils/dist:/usr/app/src/packages/utils/dist
      - ./node_modules:/usr/app/src/node_modules
    ports:
      - 3001:3001
