version: '3'
services:
  gateway:
    container_name: gateway
    build:
      context: ./
      dockerfile: ./docker-images/dev/gateway/Gateway.Dockerfile
    volumes:
      - ./services/gateway/dist:/usr/app/src/services/gateway/dist
      - ./packages/utils/dist:/usr/app/src/packages/utils/dist
      - ./node_modules:/usr/app/src/node_modules
    ports:
      - 3000:3000
    env_file: ./env/.env.dev
  ideas:
    container_name: ideas
    build:
      context: ./
      dockerfile: ./docker-images/dev/ideas/Ideas.Dockerfile
    volumes:
      - ./services/ideas/dist:/usr/app/src/services/ideas/dist
      - ./packages/utils/dist:/usr/app/src/packages/utils/dist
      - ./node_modules:/usr/app/src/node_modules
    env_file: ./env/.env.dev
  ideas-db:
    image: mongo:4.0
    ports:
      - 27017:27017