version: '3'
services:
  ideas-db:
    image: mongo:4.0
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3.7-management
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - 15672:15672
      - 5672:5672
  gateway:
    build:
      context: ./
      dockerfile: ./docker-images/production/gateway/Gateway.Dockerfile
    ports:
      - 3000:3000
    env_file: ./env/.env.production
  ideas:
    build:
      context: ./
      dockerfile: ./docker-images/production/ideas/Ideas.Dockerfile
    ports:
      - 3001:3001
    env_file: ./env/.env.production