apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: flolu/cents-ideas-gateway:latest
          env:
          - name: NODE_ENV
            value: development
          - name: IDEAS_SERVICE_HOST
            value: cents-ideas-ideas:3000
          - name: LEVEL
            value: info
          - name: RABBIT_MQ_USER
            value: rabbitmq
          - name: RABBIT_MQ_PASS
            value: rabbitmq
          - name: RABBIT_MQ_HOST
            value: cents-ideas-rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: cents-ideas-gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort