apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7-management
          env:
          - name: RABBITMQ_DEFAULT_USER
            value: rabbitmq
          - name: RABBITMQ_DEFAULT_PASS
            value: rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: cents-ideas-rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-admin
      port: 15672
    - name: amqp
      port: 5672
  type: ClusterIP
