apiVersion: v1
kind: Service
metadata:
  name: cents-ideas-gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: cents-ideas-ideas
spec:
  selector:
    app: ideas-service
  ports:
    - name: http
      port: 3000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: cents-ideas-ideas-db
spec:
  selector:
    app: ideas-db
  ports:
    - name: mongo
      port: 27017
  type: ClusterIP